spec: "0.0"
name: gadget
uuid: a6c6f893-f34c-49d4-8b48-7d01b1f41b5f
type: docker
onboot:
services:
- name: gadget
  uuid: 543d9c13-cea9-4575-a290-a6dcba514dc6
  image: ""
  directory: "../"
  net: ""
  readonly: false
  command: ['init']
  binds: ['/sys:/sys', '/data/root:/root']
  capabilities: ['SYS_RAWIO', 'SYS_ADMIN']
  devices: ['/dev/mem', '/dev/i2c-0', '/dev/i2c-1', '/dev/spidev32766.0']
